### ISSUE TITLE
Add-In Not Running

### ISSUE THREAD

**Issue by zef** [thomasa88/ParametricText#12]
I can't seem to get this Add-In to run. Similar behavior to #8, but it doesn't seem to be the same issue, as the ` thomasa88lib`  directory is populated for me...

I tried installing this initially from the app store and couldn't get the add in to run. When I press the "Run" button, the dialog simply closes, and reopening it does not show the running indicator.

Then I uninstalled the app store version, and downloaded the `v2.1.0-beta.1` zip from the releases page and manually installed it. The behavior is the same.

I have never used an Add-In before, but from what I can tell I think I've done things properly and it should be running. I'm also a developer so I'm somewhat familiar with systems like this, but I could be doing something incorrectly.

Interestingly, when I use the "Debug" option instead of "Run" from the Add-Ins window, the Run indicator is showing next to the name in the Add-Ins window, but I still don't see the option I expect in the "Modify" menu, and I don't really know how to debug the issue further without learning more.

I am on the latest version of macOS Catalina. Fusion 360 version `2.0.6041`.

Thanks for making this! I'm excited to try it out :)

![Screen Shot 2020-12-10 at 9 32 56 AM](https://user-images.githubusercontent.com/17274/101800714-cce07900-3aca-11eb-904f-6dd47cce98e4.png)

**Comment by thomasa88** [comment]
Hi,

I agree that you seem to be installing it correctly. My testing abilities on Mac are limited.

Please try this:
1. Try to start the add-in
2. Bring up Text Commands dialog (Ctrl+Alt+C on Windows, so hopefully similar on Mac)
3. Switch to "Py" mode.
4. Write "import adsk". I think any line will do, really.
5. The terminal will print any buffered print-outs at this moment. If you get any, are there any error messages?

If the above does not work, if you are prepared to install VScode. Please try the debug option and when vscode starts, press F5 to run the add-in. You should see errors in the debug console. You mentioned already trying the debug button, so maybe this does not work?

Third option: Try another add-in, just to see that add-ins run correctly.

Please try that out, and if we don't get any clues, I will see if I can add some debug dialogs in the code. (MessageBox())

Note that Fusion v2.0.9440 basically breaks my add-in, by making all texts get extreme letter-spacing. (#13 )

**Comment by zef** [comment]
Sorry — I hadn't even done the first thing I should have done when debugging this, which is to update Fusion 360!

I did that, and it is working now. I had mistakenly thought that Fusion 360 ran an auto-updater or something and I didn't even check.

Thanks a lot!
