### ISSUE TITLE
Extreme letter-spacing since Fusion 2.0.9440

### ISSUE THREAD

**Issue by thomasa88** [thomasa88/ParametricText#13]
Fusion 2.0.9440 breaks the text API, making every changed text get extreme letter-spacing.

There seems to be no way to access this property in the API, so there is no workaround.

![image](https://user-images.githubusercontent.com/89997/101873513-5786ae00-3b87-11eb-8d63-031e64cc4339.png)

Autodesk forum thread:
https://forums.autodesk.com/t5/fusion-360-api-and-scripts/cannot-select-shx-fonts-on-sketchtext-object/m-p/9923259/highlight/true#M12082

**Comment by wa0uwh** [comment]
Thomas,  Any progress or expected time frame for a fix from ParametricText or Fusion 360?

My projects are on hold, or temporarily I have removed text from parts. 
Thanks for your efforts.

**Comment by thomasa88** [comment]
Hi, @wa0uwh ,

Unfortunately, developers of add-ins don't get any extra information. What I know so far of the progress (basically nothing) is in the forum thread linked in the issue description.

I have been experimenting with reverting Fusion to an older version. Below are my draft instructions. It requires that one has an older version stored away though - if it is not possible to download another version manually.

```
Go to %localappdata%\Autodesk\webdeploy\production

Find FusionLauncher.exe.ini. This directory contains the launcher. The ini file specifies what directory contains Fusion 360.

Make a backup of the directory that the ini file points to.

To run the old version later, restore the backed up directory and point the ini file to this directory.
```

**Comment by KenLucke** [comment]
The only way I have found to correct this [by a super-kludge] after a change is to select another font, then back to the original one.  It then self corrects.  But you have to do it every single [*(%)$^^(%&%^} time

**Comment by thebeline** [comment]
> The only way I have found to correct this [by a super-kludge] after a change is to select another font, then back to the original one. It then self corrects. But you have to do it every single [*(%)$^^(%&%^} time

Also just toggling the **Bold** or *Italics* state twice works as well.

**Comment by thebeline** [comment]
@thomasa88 - It seems like there is a [weird workaround](https://forums.autodesk.com/t5/fusion-360-api-and-scripts/cannot-select-shx-fonts-on-sketchtext-object/m-p/9957431#M12199) in that forum post.  I browsed through your source code to see if I could test it, but I am *super not* familiar with Python...

**Comment by thomasa88** [comment]
I did not try the "weird" Text Commands solution as it looked like it would "manually" edit each sketch and text, which sounded like it would be very slow and also alter the gui state (is the user in the sketch edit mode or not). But thanks for trying it out! (btw, there is a Python version of the text commands interface, but it is undocumented as well. E. g. https://forums.autodesk.com/t5/fusion-360-api-and-scripts/access-section-analysis/m-p/9833126/highlight/true#M11710 ) 

I have tried to use the font change/toggle trick, mentioned by @KenLucke, but it did not fix the text spacing when executed by the API.

I have not tried using the API to change bold/italics.
I guess it would go something like this:
`text.bold = not text.bold
text.bold = not text.bold`

It sounds like you already found it, but  `set_sketch_text` is the function that does the actual sketch text update in ParametricText. 
To just try fixes, one can also just create a document with sketch text and use the commands I used to demonstrate bugs in the forum thread. 

Due to a head accident, I will not be able to do any coding or testing for some weeks :/ . My plan was to try to see if I could get the servers to give me an older version of fusion and use that in the meantime. 

By the forum thread, Autodesk has said that the next version should have a fix (hopefully, they don't break anything else this time).

**Comment by thebeline** [comment]
It actually looks more like:

```
            sketch_text.textStyle = sketch_text.textStyle ^ adsk.fusion.TextStyles.TextStyleBold
            sketch_text.textStyle = sketch_text.textStyle ^ adsk.fusion.TextStyles.TextStyleBold
```

However, this does not work.  It successfully toggles the **Bold** state, but does not rectify the issue.  I dug into the documentation for SketchText, and, yeah, nothing looks like it would affect "kerning," so I am at a loss.  Oh well.  Hopefully they get this sorted.

**Comment by thomasa88** [comment]
I did some quick tests with latest Fusion 360 (v. 2.0.9642) and I can't seem to reproduce this bug anymore.

This is also inline with the statement from Autodesk that the bug would be resolved in January updates:
https://forums.autodesk.com/t5/fusion-360-api-and-scripts/cannot-select-shx-fonts-on-sketchtext-object/m-p/9983858/highlight/true#M12290
