### ISSUE TITLE
Crash on entering parameters panel

### ISSUE THREAD

**Issue by valadas** [thomasa88/ParametricText#19]
I am trying to follow the demo video but I am getting the following error when I enter parametric text.

Any advice ?

```

---------------------------
Fusion 360
---------------------------
ParametricText v 2.1.0 error: unsupported operand type(s) for +=: 'NoneType' and 'int'

Copy this message using Ctrl+C (Windows) or take a screenshot (Mac). Describe what you did to get this error or record a video.

--------------------------------------------------

C:\Users\valad\AppData\Roaming\Autodesk\ApplicationPlugins\ParametricText.bundle\Contents\thomasa88lib\events.py failed: 

Traceback (most recent call last):
  File "C:/Users/<user>/AppData/Roaming/Autodesk/ApplicationPlugins/ParametricText.bundle/Contents\thomasa88lib\events.py", line 142, in catcher
    func(args)
  File "C:/Users/<user>/AppData/Roaming/Autodesk/ApplicationPlugins/ParametricText.bundle/Contents/ParametricText.py", line 341, in map_cmd_input_changed_handler
    add_row(table_input, get_next_id())
  File "C:/Users/<user>/AppData/Roaming/Autodesk/ApplicationPlugins/ParametricText.bundle/Contents/ParametricText.py", line 576, in get_next_id
    dialog_next_id_ += 1
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'

---------------------------
OK   
---------------------------
```

**Comment by thomasa88** [comment]
This.. shouldn't be possible.

A. 
What were your steps?
1. Create new document
2. Draw a sketch and close it. 
3. Click Change Text parameters
4. Click the + button? Just change a text? 

Did you save or re-open the document at any point? Did you switch between documents? Are you in parametric/timeline mode? 

B. 
Does this always happen? Can you export a document where it happens and attach here? (File -> Export -> f3d) 

C. 
Before opening the parameters dialog, go File -> View - > Show text console. 

Click "Py". 

Open the parameters dialog and get the error dialog. 

In the console at the bottom, type 
`True`

Copy the output you get and post here.

**Comment by valadas** [comment]
Thanks for the quick reply...

A: Strange it does work on a new document...

And wow, well today it works on the existing document, I guess yesterday 3D gods where mad at me...
