### ISSUE TITLE
Draft environment

### ISSUE THREAD

**Issue by Crazor** [thomasa88/ParametricText#2]
Can this be made to work in the draft environment? I would love to be able to pull e.g. the drawing number from the file name. Dynamic revision field in the header would be amazing, too!

**Comment by thomasa88** [comment]
I have not used the drawing environment extensible, but I assume you mean values in this block?
![image](https://user-images.githubusercontent.com/89997/93378125-449c6000-f85c-11ea-8f90-69127c7d59e8.png)

Unfortunately, it seems that scripts cannot access the drawing environment. E.g. https://forums.autodesk.com/t5/fusion-360-ideastation-archived/create-an-api-for-drawings/idi-p/7284229 .

It might be possible to do using the Command window in Fusion (can be called from scripts), but it is not very well documented. I might take a second look.

**Comment by thomasa88** [comment]
I took a quick look at the Fusion commands, but there was nothing apparent. It might be there, but it takes a lot of time figuring out the commands.

I'm leaving this issue as is for the future. Hopefully they will provide an API for the drawing environment as well.
