### ISSUE TITLE
Is there a way to make this work in Drawing mode?

### ISSUE THREAD

**Issue by johnnybeales** [thomasa88/ParametricText#28]
This isn't an issue, more like a question.
I installed this thinking it would be great to use to update version number and date on drawing sheets, sadly missing in Fusion.
After reading the documentation fully and looking at sketches on the drawing sheets I can't see an obvious way to make this work. I can make it work in the Design mode, extrude the text and add that to a drawing but not simple on multipage drawings.
Am I missing something or is the limited sketch environment in the drawing sheets limiting this clever add-in?

**Comment by thomasa88** [comment]
Hi,

Fusion 360 currently provides very limited control of the Drawing mode from add-ins. It is simply not possible to change the texts in a Drawing from an add-in. 

(For someone desperate writing add-ins who found this issue: There might be "Text Commands", but they are basically undocumented, often needs to drive UI dialogs (slow, disturbing) and are not guaranteed to work in future versions.)

**Comment by johnnybeales** [comment]
Thanks for responding, I thought that may be the case. I'll carry on with the manually updating.
