### ISSUE TITLE
text size of sketch is increased to 20,00 mm when performing save as

### ISSUE THREAD

**Issue by Turbaud** [thomasa88/ParametricText#29]
**Describe the bug**
When I save my design, the sketch which contains the _version parameter sees the text height changed form 5 mm to 20 mm during the update process
I have other sketches in the same design that don't have this problem

**To Reproduce**
1. create sketch
2. add text.
3. set text height to 5 mm
2. create text parameter that includes _version for the sketch previously created
2. apply emboss on surface
3. save design

**Expected behavior**
the text would be updated without having the text height changed

**Screenshots**
self explanatory

**Software**
 - OS: Windows 10 19043
 - Fusion 360 version: 2.0.10446
 - ParametricText version: 2.2.0

Do not forget to "Subscribe" to the issue if you want updates!

**Comment by ChrisHeerschap** [comment]
I'm seeing this exact issue, although my intended text size is 10. When I update the parameter that drives the text, the text also changes to 20mm.

**Comment by thomasa88** [comment]
Hmm, I think it might be the workaround of an old Fusion 360 bug acting up.

From the code:

>  Changing any SketchText property resets the text height
>  Bug: https://forums.autodesk.com/t5/fusion-360-api-and-scripts/bug-setting-sketchtext-properties-resets-text-height-since-v-2-0/m-p/10357593


If we assume that Fusion 360 works correctly these days (setting the text of a sketch does not reset text height), then it might work by turning the workaround off.

Can you try the following:
In ParametricText.py (you can find the install location in the add-ins dialog if you expand the bottom part) find the following line:

`text_height_workaround_state_ = WorkaroundState.Check`

Change it the following and reload the add-in (or restart Fusion 360):
`text_height_workaround_state_ = WorkaroundState.Disabled`

Does it make any difference?

**Comment by ChrisHeerschap** [comment]
Sorry for the super slow response on this, but yes! It worked! Had a model that kept reverting to 20mm, changed that workaround state from check to disabled as requested and now when I update the parameter and ParametricText updates it, the text size is preserved! Thank you!

**Comment by thomasa88** [comment]
Thanks for reporting back! I will put this in a new release (hopefully within a few days).

**Comment by thomasa88** [comment]
Published in 2.3.2 release. Submitting to Autodesk.
