### ISSUE TITLE
Installation does not work properly

### ISSUE THREAD

**Issue by greenveg** [thomasa88/ParametricText#34]
**Describe the bug**
The add-in does not show up in any way after running the installer.

**To Reproduce**
1. Downloaded package from [Autodesk App store](https://apps.autodesk.com/FUSION/en/Detail/Index?id=2114937992453312456&os=Mac&appLang=en)
2. Quit Fusion360
3. Double-click to install
4. Restart Fusion
5. Restart again
6. Rebooted macbook, still nothing.

**Expected behavior**
"Change text parameter"-option to show inside "modify" menu after restarting Fusion.

**Hardware**
2020 MacbookPro 16, Intel processor

**Software**
 - OS: MacOS Monterey 
 - Fusion 360 version: 2.0.12392 (paid)
 - ParametricText version: [v 2.2.0]

**Other info**
Plugin .bundle-file can be found at:
`/Users/johannes/Library/Application Support/Autodesk/ApplicationPlugins/ParametricText.bundle`
But nothing relating to ParametricTex is in:
`/Users/johannes/Library/Application Support/Autodesk/Autodesk Fusion 360/API/AddIns`

**Qvasi-solved**
Installed "manually" (downloaded 2.2 from git, unpacked into AddIns-directory, works fine!

**Comment by thomasa88** [comment]
The Mac installation is all confusing to me. I think Fusion 360 has two directories but one is symlinked to the other? So I think the first install location in theory should be good. It might also depend on the way Fusion was installed - from the web or from the app store(?).
The installer is created by Autodesk, so it "should work". 🤷

I'm not a Mac user, so I'm glad that you found a workaround that worked.

**Comment by greenveg** [comment]
Perhaps add the workaround to your wiki so it can be found by non-git-people?

**Comment by thomasa88** [comment]
A short note has been added to the installation section in the documentation. In 2.3.2 release.
