### ISSUE TITLE
Ability to do math

### ISSUE THREAD

**Issue by MGlaab** [thomasa88/ParametricText#35]
I'm not sure how easy it would be to add but, I would like to be able to use the values/parameters I set within Fusion 360 Parameters window to be able to do simple math within your ParametricText window. Thats not clear, here is an example. I have a simple sketch rectangle. Each side is a parameter setup in F360 Parameters(length = 2, width = 5). Now I would like to place a text box in the middle of the rectangle with the area of the rectangle(10), something that looks like this ({length}*{width}). I know I can do it manually but I would like to automate it.

**Comment by thomasa88** [comment]
Hi, since this can be easily achieved by setting a third parameter in Fusion (area = width * height) and then refer to that parameter instead, I don't think it's worth the effort of maintenance and increased usability complexity to implement this feature.

**Comment by MGlaab** [comment]
I agree, that's a much better way of doing it.
