### ISSUE TITLE
Integer parameter not evaluating in scripts (e.g. spur gear)

### ISSUE THREAD

**Issue by mik00** [thomasa88/ParametricText#37]
Please ignore this post - posted to wrong list.
I have RTFM's but not managed to figure out what I'm doing wrong, so maybe this is a bug/feature?

When I specify a spur gear using the Autodesk example add-in, I can't get it to accept **TeethN** as a parameter.  I have tried giving it the type "none" and the type "count/pieces", but both provoke the error message "The number of teeth must be a whole number".  

![image](https://user-images.githubusercontent.com/7455591/164078130-00540c6d-043d-4f63-90e5-0be046701cd9.png)

or

![image](https://user-images.githubusercontent.com/7455591/164078341-3f039369-4026-48fc-b3fb-89ca714c3e7c.png)

e.g.

![image](https://user-images.githubusercontent.com/7455591/164079233-dd9ed522-2b1d-434b-b366-58263f0379a2.png)

Mik

**Comment by thomasa88** [comment]
After reading your report twice, I fail to see how this relates to ParametricText.

If you have problems with developing add-ins, head over to the Autodesk forums: https://forums.autodesk.com/t5/fusion-360-api-and-scripts/bd-p/22

You probably want to read up on UserParameters and Parameters in the Fusion 360 API docs as well.

**Comment by mik00** [comment]
You are quite right.  It doesn't.  I can't believe I sent it to this DL.  No excuse.  I'm so very sorry for the Snafu.
Thanks for the generous advice.

**Comment by mik00** [comment]
Your response was helpful.  It encouraged me to go and root around the API
and try to understand why the demo spur gear code is so fussy.  When I
raked over the code I discovered that it did not even allow user parameters
for the tooth count.  Indeed to my limited understanding, it seems like it
is a bit of a faff to upgrade the "teeth" count variable to accept a
unitless user value, and you have to do some string parsing (shock
horror).

Thanks again.
