### ISSUE TITLE
Integer value does not work for parameters

### ISSUE THREAD

**Issue by evilC** [thomasa88/ParametricText#4]
The quick reference says:
`{_.version:03} = 024 (integer)`
Which I presume is meant to indicate that you can get an integer value of a parameter by using `:<digits>`
This seems to work OK for version, but not other units
ie here, I want the value to read `123`
![image](https://user-images.githubusercontent.com/1719428/96031966-f3c95880-0e55-11eb-9688-2366ca755618.png)
![image](https://user-images.githubusercontent.com/1719428/96032007-ffb51a80-0e55-11eb-8939-19a6b85b0598.png)
![image](https://user-images.githubusercontent.com/1719428/96032035-06dc2880-0e56-11eb-9af1-c6a1dca4d46b.png)

**Comment by thomasa88** [comment]
The Python formatter is quite complex and "03" actually means to zero-pad the value up to 3 places, while ".0f" means to format a float to have zero decimal places.

Try with this example from the README.
{width:.0f} | 6 (No decimal places)

I read through the README and realized that the v{_.version:03} (pad) and {d1:03.0f} (pad and no decimals) examples are a bit unclear on what is happening.

**Comment by evilC** [comment]
That works, thanks!
