### ISSUE TITLE
Multiple occurence of the same text

### ISSUE THREAD

**Issue by OmiCron07** [thomasa88/ParametricText#42]
I have the same text in more than one place. Is it possible to only have to change one text parameter to change it all at once, like text parameter variable reference?

![image](https://user-images.githubusercontent.com/31325575/197281212-edc33249-2d15-4e82-bc6f-ec8ed0c0159a.png)

**Comment by thomasa88** [comment]
Right now, the following options are implemented:

* When you have selected a line in the table, click on multiple sketch texts. It should look like this in the table:

Material 1, Material 2  [_PLA_______]

That is good for a static assignment.

Is it enough for your case? 


* If you want to easily change what predefined variable a certain sketch is using, a workaround is to create a variable in the "normal parameters" in Fusion 360, write something in the commend field and then use the commen with parametric text: {myfusionvar.comment}

**Comment by OmiCron07** [comment]
Marvellous! Exactly what I needed!
