### ISSUE TITLE
Text for square patterns?

### ISSUE THREAD

**Issue by evilC** [thomasa88/ParametricText#44]
I have a project which is a parametric compartmented box:
![image](https://user-images.githubusercontent.com/1719428/198317155-5f4f7174-2841-4ff3-a799-ba642f24093d.png)
You set user parameters to define the size of each compartment, and the number of rows and columns.  
The project is then set up to do a square pattern which builds the box for you.  
I was wondering if you could think of any way to allow defining of a label for each compartment (Each compartment has an embossed bit above it, in the lid) - For example, the pictured one is to store screws in, so it would be cool to be able to define labels for each screw size.  
Do you think this is technically feasible? Would it be something you would be interested in implementing?
[Edit: [Project link](https://a360.co/3z1Zc5f)]

**Comment by thomasa88** [comment]
Hi, cool project!

This sounds like a tricky problem and I would say that it is out of scope for ParametricText, as it requires more advanced capabilities.

Off the top of my head, I would say that you would want to pattern something (a sketch? a component?) that a script can find (using name prefix?) and map the text to (Calculate table x,y positions using 3D coordinates or maybe using the order/naming of the elements). Maybe the script could create the pattern and thus already know the elements.

If you're into programming, I would say look up SketchText and Design.rootComponent.sketches in the Fusion 360 API reference and go from there.
