### ISSUE TITLE
Cannot open "Change Text Parameters": "2 : InternalValidationError : control"

### ISSUE THREAD

**Issue by patl1** [thomasa88/ParametricText#47]
![image](https://user-images.githubusercontent.com/29321959/216458055-5eec4d54-b093-4015-a8db-282c0561d322.png)
I simply installed, restarted F360 abnd get this screen Win 11 on PC

**Comment by GitHubGuy89** [comment]
Same issue and error message as patl1.

Using Windows 10. Error is also similar in ParametricText v2.2.0 (line numbers are different though). 

On mine, the error message appears after going to Modify > Change Text Parameters.
After clicking OK on the error popup window, I get a blank window (see attached image)

![image](https://user-images.githubusercontent.com/20748818/216561657-dde16348-d701-4895-b109-bc4267f741ca.png)

**Comment by FerrariGuy** [comment]
I've discovered that I'm having exactly the same issue with exactly th same call back trace though I haven't used this plugin enough to know when this started occurring.  I did upgrade from 2.0.0 to try to fix the error but it is still occurring in v2.3.0 so I can only guess it has to do with either the Fusion version, or python.

![image](https://user-images.githubusercontent.com/67927155/216802289-77c1d11c-64c0-4eb5-aac3-d56bc47004c0.png)

**Comment by thomasa88** [comment]
Hi, I can reproduce the bug. It seems to been have introduced in Fusion 360 v 2.0.15291.

Upstream bug: https://forums.autodesk.com/t5/fusion-360-api-and-scripts/bug-update-now-throws-exception-setting-isfullwidth-on/m-p/11725404

Please try this fix:
https://github.com/thomasa88/ParametricText/releases/tag/v2.3.1-beta.1

(Or you can find the directory of the add-in in the Add-Ins dialog and then replace ParametricText.py with https://raw.githubusercontent.com/thomasa88/ParametricText/v2.3.1-beta.1/ParametricText.py

**Comment by patl1** [comment]
Thanks Thomas. I replaced the ParametricText.py file and it now opens in F360 without an error. I’ll mess with it today and make sure it is functioning well. Thank you for the new file and for writing the Add-in. It should be very helpful to me if it functions as I believe it will.

Pat

**Comment by patl1** [comment]
Thomas,

Worked great. Thank you

Pat

 

From: Pat and Linda Lorenz ***@***.***> 
Sent: Sunday, February 5, 2023 7:40 AM
To: 'thomasa88/ParametricText' ***@***.***>; 'thomasa88/ParametricText' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [thomasa88/ParametricText] Failure on using it (Issue #47)

 

Thanks Thomas. I replaced the ParametricText.py file and it now opens in F360 without an error. I’ll mess with it today and make sure it is functioning well. Thank you for the new file and for writing the Add-in. It should be very helpful to me if it functions as I believe it will.

Pat

**Comment by GitHubGuy89** [comment]
The new ParametricText.py from v2.3.1-beta.1 is working for me as well.

I didn't extensively test it, but so far it seems to be doing what it's supposed to.

Thank you!

**Comment by thomasa88** [comment]
Thanks for testing!

Fusion has released a fix for the original. Fusion 360 v. 2.0.15299 no longer has the bug.
