### ISSUE TITLE
parametric text issue

### ISSUE THREAD

**Issue by nattybyrne** [thomasa88/ParametricText#50]
I am getting the following error message when I use the change parameters option in fusion 360,
I got a file from a friend and that changing one of the parameters to change a radius and also it is meant to change the radius written on the product
however when I click on OK, on parameters i get this message:
I have installed from the autodesk fusion 360 app store plugin:
"ParametricText"
Some screen shots below include what done / happen with extra text, i entered on them.

See https://forums.autodesk.com/t5/fusion-360-support/parameters-with-parametric-text-plugin/m-p/11824148#M170295, where i have got some pictures to assist

ParametricText v 2.3.0 error: 5 : MoveFace1 / Compute Failed // ASM_REBL_REMOVE_FAILED - An existing fillet or chamfer could not be deleted.
Try suppressing or deleting existing fillets/chamfers before attempting the operation. // ASM_REBL_REMOVE_FAILED - An existing fillet or chamfer could not be deleted.
Try suppressing or deleting existing fillets/chamfers before attempting the operation.
Copy this message by taking a screenshot. Describe what you did to get this error or record a video.
--------------------------------------------------
Fusion 360 v. 2.0.15509
C:\Users\Nathaniel\AppData\Roaming\Autodesk\ApplicationPlugins\ParametricText.bundle\Contents\thomasa88lib\events.py failed:
Traceback (most recent call last):
File "C:\Users/<user>/AppData/Roaming/Autodesk/ApplicationPlugins/ParametricText.bundle/Contents\thomasa88lib\events.py", line 142, in catcher
func(args)
File "C:/Users/<user>/AppData/Roaming/Autodesk/ApplicationPlugins/ParametricText.bundle/Contents/ParametricText.py", line 1362, in update_cmd_execute_handler
update_texts(*async_update_queue_.get())
File "C:/Users/<user>/AppData/Roaming/Autodesk/ApplicationPlugins/ParametricText.bundle/Contents/ParametricText.py", line 1322, in update_texts
text_updated = set_sketch_text(sketch_text, evaluate_text(text, sketch_text, next_version))
File "C:/Users/<user>/AppData/Roaming/Autodesk/ApplicationPlugins/ParametricText.bundle/Contents/ParametricText.py", line 711, in set_sketch_text
check_text_height_bug(sketch_text)
File "C:/Users/<user>/AppData/Roaming/Autodesk/ApplicationPlugins/ParametricText.bundle/Contents/ParametricText.py", line 790, in check_text_height_bug
sketch_text.height = test_height
File "/packages\adsk\fusion.py", line 74886, in _set_height
return _fusion.SketchText__set_height(self, value)
RuntimeError: 5 : MoveFace1 / Compute Failed // ASM_REBL_REMOVE_FAILED - An existing fillet or chamfer could not be deleted.
Try suppressing or deleting existing fillets/chamfers before attempting the operation. // ASM_REBL_REMOVE_FAILED - An existing fillet or chamfer could not be deleted.
Try suppressing or deleting existing fillets/chamfers before attempting the operation.

**Comment by thomasa88** [comment]
Hi,

This message is from Fusions engine:
"MoveFace1 / Compute Failed // ASM_REBL_REMOVE_FAILED - An existing fillet or chamfer could not be deleted.
Try suppressing or deleting existing fillets/chamfers before attempting the operation

"

My guess that it is triggered when ParametricText tries to do Compute All.

What happens if you just open the file and do Compute All in Fusion? (Ctrl+B)
Any errors?

If not, what happens if you first disable ParametricText in the add-ins dialog, then change your intended radius and then update the text manually, by editing the sketch. Any errors from fusion? Errors after Compute All?
