### ISSUE TITLE
parameter modification via API / script --> update not working

### ISSUE THREAD

**Issue by andreas-rapid-ood** [thomasa88/ParametricText#54]
issue
The change of a parameter comment via graphical user interface (change parameters) is working flawless. However if you update the related comment via API / script it will not be updated in the geometry (but the comment itself is updated)

1. change paraemter comment via API (example: Param.comment = 'PPP')
2. execute script. parameter comment is changed successfull
3. double check geometry: Geometry not updated by ParametricText plugin
4. workaround (as proposed): open "modify/change text parameters" in graphical user interface and hit "OK" --> update done

Expected behavior
update of geometry should be done by script directly to give the ability to process the updated geometry within the script (save as for example)
--> a workaround to "open and klick OK" on the ParametricText feature via API / script would also be appreciated

Screenshots
![image](https://github.com/thomasa88/ParametricText/assets/115020505/aa4ba86e-759e-4fb7-a80e-13a430d6ebfd)
![image](https://github.com/thomasa88/ParametricText/assets/115020505/970c92c9-6ab8-4da2-8960-dddb76e66cce)

**Software**
 - OS: Windows
 - Fusion 360 version: 2.0.15509
 - ParametricText version: v 2.30

thanks for any help or hints

**Comment by thomasa88** [comment]
Hi, can you try the suggestion in this issue?

https://github.com/thomasa88/ParametricText/issues/39

**Comment by andreas-rapid-ood** [comment]
Hi Thomas,

thanks for that hint. I have to apologize not to have tried that first. I simply did not found it by reading through the existing topics.
I tried to implement it into my existing script (which has to be developed but works flawless until now) and fusion is executing the script including export and  message box but than crashes. The geometry is not updated. Is it correct that "UPDATE_CMD_ID = 'thomasa88_ParametricText_Update'" is basically doing what you suggest as UI workaround (open "modify/change text parameters" in graphical user interface and hit "OK")?

below my small script. Goal is updating a specific part including a text and store it as 3mf 

import adsk.core, adsk.fusion, adsk.cam, traceback
#import os.path, sys

def run(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui = app.userInterface
        design = adsk.fusion.Design.cast(app.activeProduct)
        
        # Get the root component of the active design
        rootComp = design.rootComponent

        # Specify the folder to write out the results.
        folder = 'C:/data/R-OOD/design/validation/'

        # Get the parameters to change.
        p_1_Param = design.allParameters.itemByName('p_1')
        p_2_Param = design.allParameters.itemByName('p_2')

            
        p_1 = 31
        p_2 = 'PPP'
        p_1_Param.expression = str(p_1)
        p_2_Param.comment = str(p_2)

        #update parametric text plugin
        UPDATE_CMD_ID = 'thomasa88_ParametricText_Update'
        update_cmd_def = ui.commandDefinitions.itemById(UPDATE_CMD_ID)
        update_cmd_def.execute()
                
        # Construct the output filename.
        filename = folder + 'fusion360.3mf'

        # Save the file as 3mf.
        exportMgr = adsk.fusion.ExportManager.cast(design.exportManager)
        Options3mf = exportMgr.createC3MFExportOptions(rootComp)
        Options3mf.filename = filename
        exportMgr.execute(Options3mf)

        ui.messageBox('script finished, comment changed to')

**Comment by thomasa88** [comment]
I had a quick play-around with your script and I'm also seeing the crash.

I did an attempt with an alternative solution, using a Custom Event.

Please check out the `ext-trigger` branch and try the following code. I have not really tried this, except to see that the text update gets called and that Fusion 360 does not crash.

```
#Author-
#Description-

import adsk.core, adsk.fusion, adsk.cam, traceback

def run(context):
    ui = None
    app = adsk.core.Application.get()
    ui = app.userInterface
    design = adsk.fusion.Design.cast(app.activeProduct)

    app.fireCustomEvent('thomasa88_ParametricText_Ext_Update')
        
    adsk.doEvents()
    adsk.doEvents()

    ui.messageBox('script finished, comment changed to')

```

For some reason, I had to run the event loop twice (doEvents) for the ParametricText custom event to get triggered.

**Comment by Pommes1024** [comment]
The ext-trigger branch works for me! Will it be forwarded to the current build?

**Comment by thomasa88** [comment]
In 2.3.2 release.

**Comment by thomasa88** [comment]
To everyone wanting to force a refresh using scripts. Have you considered that, depending on your setup, it might be easier to just change the text in the sketch using app.activeProduct.rootComponent.sketches[0].texts[0]  :)   (Written from memory as I don't have access to a computer at the moment)
