### ISSUE TITLE
Add _.configuration 

### ISSUE THREAD

**Issue by thomasa88** [thomasa88/ParametricText#58]
From store comments:
"Very happy I found this AddIn. I'm wondering if there is a way to add "_.configuration"? I'm hoping to use each configuration's name as text."

Upcoming Fusion 360 will have support for configurations in the API. Add `_.configuration`.

**Comment by thomasa88** [comment]
Need assistance from a user that does not have the hobbyist license. When support for configurations in the API is released in Fusion, there can be an investigation.

**Comment by Paulomart** [comment]
Hey, do you still need a file containing a configuration setup? If so I can send you an email with a sample project from me.

**Comment by thomasa88** [comment]
Hi, I managed to find a project with a configuration on the Autodesk forums, but it seems that I cannot even inspect it with my license.

Instead, I would need help to run some API code. I've been scraping the [Autodesk docs](https://help.autodesk.com/view/fusion360/ENU/?guid=GUID-D3032AC7-E47F-42B6-BE66-ADB8F3DCF7A1) for info. I have found some configuration-related commands. However, I have not found a way to a) determine which configuration is the active one and b) read the names of the configurations (I think).

The below code is _one line_. Could you open Text Commands (Ctrl+Alt+C), select "Py", paste the line and then press enter. Then please paste the result here.

If you hover over the code below, a _copy_ button should appear to the right.
```
[exec(f"print('{e}:')\ntry: print({e})\nexcept Exception as ex: print(ex)") for e in ["adsk.core.Application.get()", "adsk.core.Application.get().activeDocument.dataFile.isConfiguredDesign", "adsk.core.Application.get().activeDocument.dataFile.configurationTable", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.id", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.rows", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.rows[0]", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.rows.item(0).getCellByColumnIndex(0)", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.rows.item(0).getCellByColumnIndex(1)", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.rows.item(0).getCellByColumnIndex(2)", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.rows.item(0).getCellByColumnIndex(3)", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.rows.item(0).getCellByColumnIndex(4)", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.getCell(0, 0)", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.getCell(0, 0).objectType", "adsk.core.Application.get().activeDocument.dataFile.isConfiguration", "adsk.core.Application.get().activeDocument.dataFile.configurationRowId"]]
```

**Comment by Paulomart** [comment]
Here is the same output from windows. Seems like it dosent make a difference:

```
[exec(f"print('{e}:')\ntry: print({e})\nexcept Exception as ex: print(ex)") for e in ["adsk.core.Application.get()", "adsk.core.Application.get().activeDocument.dataFile.isConfiguredDesign", "adsk.core.Application.get().activeDocument.dataFile.configurationTable", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.id", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.rows", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.rows[0]", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.rows.item(0).getCellByColumnIndex(0)", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.rows.item(0).getCellByColumnIndex(1)", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.rows.item(0).getCellByColumnIndex(2)", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.rows.item(0).getCellByColumnIndex(3)", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.rows.item(0).getCellByColumnIndex(4)", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.getCell(0, 0)", "adsk.core.Application.get().activeDocument.dataFile.configurationTable.getCell(0, 0).objectType", "adsk.core.Application.get().activeDocument.dataFile.isConfiguration", "adsk.core.Application.get().activeDocument.dataFile.configurationRowId"]] 

```

**Comment by thomasa88** [comment]
Thanks for taking the time to check this. It looks like only parts of the functionality is implemented so far (getting tow, but not getting cell).

I guess we just have to wait.

**Comment by thomasa88** [comment]
It looks like kandennti on the forums found a way!

Can you try this command?

```
adsk.core.Application.get().activeProduct.configurationTopTable.activeRow.name
```

If that works, can you try the following on a design without a configuration (want to be able to handle that user error):
```
adsk.core.Application.get().activeProduct.configurationTopTable
```

**Comment by Paulomart** [comment]
> adsk.core.Application.get().activeProduct.configurationTopTable.activeRow.name

```
Konfiguration 2
```

> adsk.core.Application.get().activeProduct.configurationTopTable

```
adsk.core.Application.get().activeProduct.configurationTopTable

x = adsk.core.Application.get().activeProduct.configurationTopTable == None 

x 
True
```

>

**Comment by thomasa88** [comment]
Thanks!

Can you try downloading this version of ParametricText.py and put it in the add-in folder (take a backup copy of the original file first).

https://raw.githubusercontent.com/thomasa88/ParametricText/2889b88af398042246037f76e6cba841419d6f58/ParametricText.py

`_.configuration` should work.


I expect the file to be here if you used the Autodesk installer:
C:\Users\YOUR_USERNAME\AppData\Roaming\Autodesk\ApplicationPlugins\ParametricText.bundle

**Comment by Paulomart** [comment]
Works like a charm! Thanks a lot!

**Comment by thomasa88** [comment]
Great! Note that this API feature is stilled marked _experimental_ by Autodesk, so it might break in the future.

Hmm, some more thoughts:
* Does the text update correctly if you change which configuration is the active one?
* Does the text update if the configuration is renamed?

If any of those is problematic, could you try running the troubleshooting code described here: https://github.com/thomasa88/ParametricText/issues/56#issuecomment-1656566754

**Comment by Paulomart** [comment]
> Does the text update correctly if you change which configuration is the active one?

Yes

> Does the text update if the configuration is renamed?

No 

Here is the debug output:

```
x 
ParametricText terminate: SelectCommand, reason: 4
ParametricText terminate: MarkDocumentsForOpenCommand, reason: 2
ParametricText terminate: PLM360OpenAttachmentCommand, reason: 2
ParametricText terminate: CloseDocumentCommand, reason: 2
ParametricText terminate: SelectCommand, reason: 5
ParametricText terminate: SelectCommand, reason: 4
ParametricText terminate: MarkDocumentsForOpenCommand, reason: 2
ParametricText terminate: PLM360OpenAttachmentCommand, reason: 2
ParametricText terminate: CloseDocumentCommand, reason: 2
ParametricText terminate: SelectCommand, reason: 5
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'x' is not defined


# changing configuration now 
invalid syntax (<string>, line 1)

# changing configuration name now 
ParametricText terminate: SelectCommand, reason: 4
ParametricText terminate: DesignConfigurationActivateRowCmd, reason: 1
ParametricText terminate: SelectCommand, reason: 4
ParametricText terminate: thomasa88_ParametricText_Update, reason: 1
ParametricText terminate: SelectCommand, reason: 4
ParametricText terminate: DesignConfigurationActivateRowCmd, reason: 1
ParametricText terminate: SelectCommand, reason: 4
ParametricText terminate: thomasa88_ParametricText_Update, reason: 1
invalid syntax (<string>, line 1)

# changed configuration name  
ParametricText terminate: SelectCommand, reason: 4
ParametricText terminate: FusionStartDesignConfigModeCmd, reason: 2
ParametricText terminate: SelectCommand, reason: 4
ParametricText terminate: DesignConfigurationCmd, reason: 2
ParametricText terminate: DesignConfigurationToolbarCmd, reason: 2
ParametricText terminate: CloseConfig, reason: 2
ParametricText terminate: DesignConfigurationUpdateNestedRowNameCmd, reason: 2
invalid syntax (<string>, line 1)

# changing configuration now again 
invalid syntax (<string>, line 1)

# done 
ParametricText terminate: SelectCommand, reason: 4
ParametricText terminate: DesignConfigurationActivateRowCmd, reason: 1
ParametricText terminate: SelectCommand, reason: 4
ParametricText terminate: thomasa88_ParametricText_Update, reason: 1
invalid syntax (<string>, line 1)
```

**Comment by thomasa88** [comment]
Hi, I've been quite busy the last month. Please try this new version:
https://github.com/thomasa88/ParametricText/blob/15064508243a38636ef5e3a2040b70b1a363e33e/ParametricText.py

It listens for "DesignConfigurationUpdateNestedRowNameCmd" cancelled(!) which seems to appear when you change the name.

**Comment by Paulomart** [comment]
> Please try this new version

Just tried it out and it works. Awesome!

Thanks :)

**Comment by thomasa88** [comment]
Part of 2.4 release. Submitted to Autodesk.
