### ISSUE TITLE
Scripting the parameters & Model not updated

### ISSUE THREAD

**Issue by pagman** [thomasa88/ParametricText#6]
Hello, awesome plug in thank you ! i have the question can this be used with a python automation script ? and if yes can you please give us a sample?

**Comment by thomasa88** [comment]
Hi @pagman,

I'm not sure that I understand your use case. Maybe you can elaborate?

If you want to automate text assignment I would skip this add-in and use the Fusion APIs directly.

Some direct links  (will likely die in a while..):
SketchText  object:  http://help.autodesk.com/view/fusion360/ENU/?guid=GUID-265d4bb3-2e68-4edf-bd57-bb4d4204beb0

design.rootcomponent: http://help.autodesk.com/view/fusion360/ENU/?guid=GUID-ce33611e-ba91-484d-88b1-8eb2cec47be2

Also check the user manual on how to write scripts and add-ins: http://help.autodesk.com/view/fusion360/ENU/?guid=GUID-9701BBA7-EC0E-4016-A9C8-964AA4838954

**Comment by pagman** [comment]
Thank you for the answer! I am still facing the problem after I change the parameters from your addin doesn't baffect the model if it don't press compute all...any idea why?

**Comment by thomasa88** [comment]
1. Do you mean that the sketch text does not change or the features dependent on the text do not update?
2. Which version of Fusion 360 are you using?
3. Which version of ParametricText are you using?
4. Are you using Mac or Windows?
5. Also, can you provide an example file where this is happening?

I have mostly used extrude cut on flat surfaces and I have not yet encountered this issue.

**Comment by pagman** [comment]
1. i mean the features dependent on the text do not update ntil i  hit comput all ( ctrl+ b)
2.i am using 2.0.9144 fusion version 
3. the V2 didnt work at all it gives me errors. but it does it with v1 and v1.1
4. windows
i dont want to bother you and take your time i have made the automation that i wanted with a script

**Comment by thomasa88** [comment]
I want to know if there are any bugs, so the bug reporting is not a bother :). I really want V2 to be stable. 

Anyway, I'm glad that you found a workflow that works. If you wouldn't mind and if it is not too troublesome, would you be able to take a screenshot of the error with V2?

**Comment by thomasa88** [comment]
Hi, I just pushed v2.0.0-beta.5, which runs Compute All automatically. Hope it works good!

https://github.com/thomasa88/ParametricText/releases
