### ISSUE TITLE
Text Doesn't Update on Model Geometry when Parameter Value is Changed by Script/Add-In

### ISSUE THREAD

**Issue by ektomorph** [thomasa88/ParametricText#60]
**Describe the bug**
The text parameter value does not change on the model when its value is changed by a script/add-in.

**To Reproduce**
I've been using both the ParaParam script as well as a custom-written script to successfully change other parameters and have their geometry updated accordingly, but the change is not applied when using it to automate the change the value of parametrized text.  The values change in the Parameters Table as they should, but the model will not update unless the value is changed in the parameter table itself.

1. Parameter Comment is changed via script.
2. Script is executed, values in Parameter Table update accordingly, files are exported accordingly.
3. Geometry is not changed, values on model different from values in Parameter Table.
4. Model geometry doesn't change unless a DIFFERENT value is set as the parameter via parameter table and OK is clicked.

Expected behaviour: The script iterates through a series of parameter values, and the parametrized text values should change with it.  

![image](https://github.com/thomasa88/ParametricText/assets/159194174/6f64aacf-f39f-49a6-9e7e-93b6832f68e5)
This image shows the original value, 401, set as the ID number.

![image](https://github.com/thomasa88/ParametricText/assets/159194174/5fa5173e-6b27-4180-8a90-0c504ae12f86)
This image shows the range of values to be iterated through and exported; 300 through 305. 

![image](https://github.com/thomasa88/ParametricText/assets/159194174/8f910987-48b6-4a98-bb16-fefbb609671d)
This image shows the parameter table and model after iteration; the values have been iterated through appropriately, but the model geometry shows the original value (and different from that in the parameter table).

I recognize that this is the same challenge as in issues #39, #54, and #57 and was addressed in v2.3.2, though none of the suggested solutions have been successful for me (including a complete reinstallation of Fusion 360 as well as the add-in via the Fusion App Store and Github).

**Software**
 - OS: macOS Monterey, 12.6.8
 - Fusion 360 version: Fusion 2.0.18441 x86_64 [Native] 
 - ParametricText version: v2.3.3

Do not forget to "Subscribe" to the issue if you want updates!

**Comment by thomasa88** [comment]
Hmm, so you are saying that `app.fireCustomEvent('thomasa88_ParametricText_Ext_Update')` does not have any effect?

What if you add `adsk.doEvents()` after it? Possibly twice. :thinking: 

And you don't get any errors? (What if you open the console (ctrl+alt+C), select Py and write `1`. Any errors printed?)

**Comment by ektomorph** [comment]
Okay, so I'm sufficiently embarrassed and humbled by this whole experience.  The iterating script I was using would only update the tables but it would never actually use `_app.fireCustomEvent('thomasa88_ParametricText_Ext_Update')`.  It seems that it wasn't ever being called, and therefore wouldn't update the geometry properly.

I found the part in my iterating script with `adsk.doEvents()`, put fireCustomEvent ahead of that, and now the two scripts were talking to each other!  I still had further challenge where it wasn't exporting properly, but putting `ads.doEvents()` a second time made it work.

So the solution so far (and for anyone else reading this...)

1. `_app.fireCustomEvent('thomasa88_ParametricText_Ext_Update')` added before `adsk.doEvents()` in **iterating script**
2. `adsk.doEvents()` added a second time immediately after the first.

I'll keep running it and see if we get any weird size bugs, but so far this seems to do it.

You're awesome.  Thank you very much!

**Comment by Andrew553328** [comment]
Good morning Thomas :)

        # set the text for this puzzle
        allow_text=True
        design.userParameters.itemByName('t_label').comment='HEXX.au'
        design.userParameters.itemByName('t_ID').comment=t_p+'-'+t_a+'-'+t_crc
        design.userParameters.itemByName('t_level').comment=t_val

        # as advised by the author Feb 2024
        app.fireCustomEvent('thomasa88_ParametricText_Ext_Update')
        adsk.doEvents()
        adsk.doEvents()  

Works as expected. Thank you :))

Comment...I have found it very difficult to find methods in Fusion 360
A search for firecustomevent does not appear in your code, **it would be a very useful note to appear in your code**

**Comment by thomasa88** [comment]
Good idea! I'll see if I can add it somewhere.

**Comment by Andrew553328** [comment]
Thank you for your prompt responses Thomas :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jomixlaf** [comment]
Same here and Thomas response solved my issu as well, this is insanely nice saving time, thank you very much jesus programmer

**Comment by thomasa88** [comment]
Part of 2.4 release. Submitted to Autodesk.

**Comment by bec-archer** [comment]
Hi there, I am having the same issue. Mac OS 15.5, current version of Fusion, tried the above fix and it didn't work. Any help would be appreciated!
