### ISSUE TITLE
Trying to change 512 texts uses to much resources even on an Apple M2 Mac

### ISSUE THREAD

**Issue by AWSW-de** [thomasa88/ParametricText#62]
Hi Thomas,

first of all MANY THANKS for this great plugin! You can't believe how much time it saved me on my last [WordClock 16x8 project](https://www.printables.com/de/model/749967-wordclock-16x8-2024) in meanwhile 11 languages and 3 fonts. =) 

**Describe the bug**
- Currently I am working on my 2024 variant of my [WordClock 16x16](https://www.printables.com/de/model/331012-wordclock-16x16-led-matrix) which should have 4 different fonts on the front in different languages too.
- As shown in the picture there are 512 text fields containing 1 letter each which are feed through the parameters list of course. I import the content of the parameters list with the "Parameter I/O" plugin with the help of a .CSV file and save the project in Fusion.
- Then I open up your plugin and use OK to start the update process. 
- On the 16x8 variant of the project it worked fine to update 3 fronts with 128 texts each at once within around 50 minutes per language. 
- With the shown 16x16 variant it seems to be more complicated. After about 1 hour the attached resource warning shows up and Fusion stops working even on an Apple M2 Mac with 24GB of RAM. 
- I already separated the 4 fronts to update 1 at the time with 512 texts only which helped to update 2 of the 4 fronts. Strange to me, because the difference between them is the used font and font size only, so it somehow seems to be related on the used font (?!?)...

**Screenshots**
![Bildschirmfoto 2024-02-16 um 09 30 06](https://github.com/thomasa88/ParametricText/assets/34800740/c740eaa5-2c97-473f-8dec-0ad4654e14de)

Hope you have some hints for me how to solve this. 

Thanks in advance and kind regards =)

**Software**
 - OS: macOS 14.3.1 Apple M2 - 24GB
 - Fusion 360 version: 2.0.18441 arm64 [Native] 
 - ParametricText version: 2.3.1 and 2.3.3

**Comment by thomasa88** [comment]
Hi, my intention with ParametricText is for it to fill in a small number of texts and I have not looked at how the performance scales. With that many texts I think you might be better of just creating an API script of your own, accessing each SketchText: https://help.autodesk.com/view/fusion360/ENU/?guid=GUID-265d4bb3-2e68-4edf-bd57-bb4d4204beb0

```
app=adsk.core.Application.get()
app.activeProduct.rootComponent.sketches[0].sketchTexts[0]
```

Of course, you will have to solve the problem of assigning texts in the correct order..

**Comment by AWSW-de** [comment]
Hi, 
thanks for your answer which I expected a little bit in advance. 
The link you provided seems to be dead, so I can’t follow it.  
Thanks a lot and have a nice day. Kind regards. :)

**Comment by thomasa88** [comment]
The links break when they do updates. :S

Try searching for "SketchText.angle" on that page and then you can step back up to SketchText, if you feel like digging into some Python. :) 

Closing this report.
