### ISSUE TITLE
Add part number and description fields to _.xxxx options

### ISSUE THREAD

**Issue by phyxius1** [thomasa88/ParametricText#65]
It would be great if it was possible to pull in the Part Number and Description fields from the Fusion part properties.  I'm using the text parameters to label parts, and this would be very helpful.

**Comment by thomasa88** [comment]
Hi, Part description is added to master as `_.compdesc` (from https://github.com/thomasa88/ParametricText/pull/63 ). It will appear in version 2.4, which I hope to release within the coming weeks.

I will look into the part number field.

**Comment by thomasa88** [comment]
Part of 2.4 release. Submitted to Autodesk.
